### ISSUE TITLE
Speaker images show up broken

### ISSUE THREAD

**Issue by Matthewsre** [SeattleCodeCamp/WebSite#24]
Broken images are showing up for users without twitter images or twitter accounts

**Comment by slobo80** [comment]
It appears that the app is saving the image to the file system. Since Azure websites are stateless, the image is gone as soon as the website is recycled. Clearly, the app is not built for stateless environment. Even though blob storage would probably be a better candidate, I prefer to keep it simple and store the images in the SQL database.

**Comment by Matthewsre** [comment]
Started on this, the ImageUrl is used in a bunch of places and I have to track them all down to use some tiered logic for the final URL resolution. Image is being added to the Person object to store in the DB.

**Comment by slobo80** [comment]
Since I made the changes to sponsor images, how they are stored and rendered, you may be able to reuse some of that code.

**Comment by devin5885** [comment]
I'm working on this one.

**Comment by devin5885** [comment]
Do we need to consider existing users? (i.e.) will the registered user list from previous years be maintained?

**Comment by slobo80** [comment]
@devin5885 Yes. User register once and after that every year they only need to RSVP for that year's code camp.

**Comment by devin5885** [comment]
Some of the code I need to change is related to external login, however since I don't have our external login credentials, I can't enable this functionality. Is there a way to test this or do we have test keys?

**Comment by slobo80** [comment]
Thx for addressing this issue.
