### ISSUE TITLE
Admin should be able to maintain topics

### ISSUE THREAD

**Issue by slobo80** [SeattleCodeCamp/WebSite#5]
Speaker can register a new session when logged in. Session registration page contains a "topic" drop down list which is sourced from Tags table. However, there is no page to maintain this table. We have to manually enter Tags into the database.

**Comment by cmichaelhansen** [comment]
I can take this one.

**Comment by cmichaelhansen** [comment]
Question on implementation. Since the tags are a FK into the Session table, do we want the code to remove the FK as well when a tag is deleted or do we want to ensure no sessions currently have the related tag and inform the user (admin) when trying to delete?

My preference would be to return a list of sessions that currently use the tag when trying to delete an in use tag. Thoughts?

**Comment by slobo80** [comment]
Go with your preference.

**Comment by cmichaelhansen** [comment]
Actually I noticed that we are showing counts of sessions that use tags, so I just adopted that approach.

When viewing the Tags, you can delete those that are not assigned to any sessions, and it also displays a count of the sessions for each tag. It's fairly simple, but at least you won't have to manually enter them in the database. I'll commit once I clean up the html on the index view.
