### ISSUE TITLE
Modifying volunteer task does not work

### ISSUE THREAD

**Issue by slobo80** [SeattleCodeCamp/WebSite#7]
Editing a volunteer task from the admin menu does not load all the task info correctly. Also, saving the updated info does not save to the db.

**Comment by Matthewsre** [comment]
I have started on this in a local branch, taking a little longer than I expected

**Comment by Matthewsre** [comment]
Fix submitted in pull request

**Comment by cmichaelhansen** [comment]
Checking on status of this issue, does it still need fixing?

**Comment by slobo80** [comment]
Looks like Matt has worked on it. Can you test it and close the issue if fixed?

**Comment by cmichaelhansen** [comment]
I still see the issue in the latest code. Matt mentions he has a fix in a pull request, but I don't see any outstanding pull requests. I'm happy to fix it.

**Comment by slobo80** [comment]
Go ahead and fix it.

**Comment by Matthewsre** [comment]
This was an issue with the dates that I put a fix in for. I'll double check this tonight

Sent from my Windows Phone

**Comment by cmichaelhansen** [comment]
Ok, I re-tested it this morning and I think the only remaining issue is the initial value in the task start/end times. As long as that gets changed then it works ok. I'll double-check the editing issue as well.

I went ahead and added a datetimepicker to the boxes and upgraded jquery to 1.7 in order to use it. I need to clean things up a little, but it should make the entering of the start/end times a bit easier. Coming soon in my next pull request.

**Comment by cfranciscodev** [comment]
This seems to be working as expected, I think it can be closed now.

**Comment by slobo80** [comment]
Closing the issue as it appears to be fixed.
